export const chilliVarieties = [
  {
    id: "teja-stem-deluxe",
    name: "S17/Teja with Stem Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Deluxe (AAA)",
    description: "Premium hand-sorted Teja S17 with long stems. Boasts high pungency, uniform bright red color, and excellent luster.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemcut-deluxe",
    name: "S17/Teja Stemcut Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "Stemcut",
    grade: "Deluxe (AAA)",
    description: "Carefully trimmed Teja S17. Stems are cut short to optimize packaging volume while maintaining premium pod quality.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemless-deluxe",
    name: "S17/Teja Stemless Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Deluxe (AAA)",
    description: "Premium hand-destemmed Teja S17. Completely free of stems and stalks, ready for grinding and oleoresin extraction.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmXIAenfi-O4aUICculJkb2c_q1geKDxYKitxFEKv9tYDEzwOveyD5RzHKwfV9ieXSc324FGyYwKG-jN-kFhmH633Psk8W6m8oliB8ZwQFdEiESIKHTAZCytcJUq672sifKtvQjWFfOqZg1PzYQKFf9BDx3MAn6Tb7mXzu8v9CjDRXdcNnB6mfaQpvdVsf0Pwnw7oZV6PJWXsGHDJSKIAHuWVb0Tm-JM2VLtgXNN8g-8-U-u5GU-dGDxb8d5jpzPknAHbWwrqOIuk"
  },
  {
    id: "teja-stem-best",
    name: "S17/Teja with Stem Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Best (AA)",
    description: "Standard grade Teja S17 with stem. Offering high heat value and rich flavor at a competitive wholesale price.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemcut-best",
    name: "S17/Teja Stemcut Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "Stemcut",
    grade: "Best (AA)",
    description: "Standard grade Teja S17 with cut stems. Provides excellent pungency and optimized packing efficiency.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemless-best",
    name: "S17/Teja Stemless Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Best (AA)",
    description: "Wholesale grade stemless Teja S17. Hand-cleaned to remove stalks, ideal for commercial spice processors.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmXIAenfi-O4aUICculJkb2c_q1geKDxYKitxFEKv9tYDEzwOveyD5RzHKwfV9ieXSc324FGyYwKG-jN-kFhmH633Psk8W6m8oliB8ZwQFdEiESIKHTAZCytcJUq672sifKtvQjWFfOqZg1PzYQKFf9BDx3MAn6Tb7mXzu8v9CjDRXdcNnB6mfaQpvdVsf0Pwnw7oZV6PJWXsGHDJSKIAHuWVb0Tm-JM2VLtgXNN8g-8-U-u5GU-dGDxb8d5jpzPknAHbWwrqOIuk"
  },
  {
    id: "s4-stem-deluxe",
    name: "S4/334 with Stem Deluxe",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Deluxe (AAA)",
    description: "Premium Guntur Sannam S4 variety with stem. Selected for thick skins, moderate heat, and brilliant red appearance.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stemless-deluxe",
    name: "S4/334 Stemless Deluxe",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Deluxe (AAA)",
    description: "Top-tier S4 Guntur Sannam without stems. Manually destemmed, preserving clean pods for blending and packaging.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stem-best",
    name: "S4/334 with Stem Best",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 80 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Best (AA)",
    description: "Standard trade quality S4 Guntur Sannam with stem. Excellent value for regular commercial grinding.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stemless-best",
    name: "S4/334 Stemless Best",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 80 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Best (AA)",
    description: "Destemmed S4 Guntur Sannam, standard grade. Cost-effective and ready for pulverization in spice mills.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s10-stem",
    name: "S10 with Stem",
    category: "S10",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "S10 variety with stem intact. Offers a mild heat footprint combined with deep red pigmentation for balanced blends.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBz2O0Bku-uk1bIOLFsFezwkTk5kKyMeZbSuxeXTXF--b-6-CimtTXBKga8abM8zNGJindfw-M9BclCuLU9jsmB-1jkM83e-lejWE3pum_MTSihb_ebDcpotQUFq4ki1J8sw-BWRW7pOHPyFDRWazhdirUVX0F67s_5li3HSDFd3CsryW6zcFn7pk_ZWTx_8er_A-A2xi-JAJbCEyLovmwG9uRvba0KKcOvXUMlzFsaa5FlF3v1L0n3MgltJXI8TIw-sVG7Brk9SPQ"
  },
  {
    id: "s10-stemless",
    name: "S10 Stemless",
    category: "S10",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Standard (A/AA)",
    description: "Stem-free S10 pods. Provides bright red color values and mild heat, highly suitable for generic seasoning powders.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBz2O0Bku-uk1bIOLFsFezwkTk5kKyMeZbSuxeXTXF--b-6-CimtTXBKga8abM8zNGJindfw-M9BclCuLU9jsmB-1jkM83e-lejWE3pum_MTSihb_ebDcpotQUFq4ki1J8sw-BWRW7pOHPyFDRWazhdirUVX0F67s_5li3HSDFd3CsryW6zcFn7pk_ZWTx_8er_A-A2xi-JAJbCEyLovmwG9uRvba0KKcOvXUMlzFsaa5FlF3v1L0n3MgltJXI8TIw-sVG7Brk9SPQ"
  },
  {
    id: "byadgi-stem",
    name: "Byadgi with Stem",
    category: "Byadgi",
    heatLevel: "8,000 - 15,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Premium Byadgi chillies with stem. Characterized by deeply shrivelled pods, low heat, and exceptionally high ASTA color values.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "byadgi-stemless",
    name: "Byadgi Stemless",
    category: "Byadgi",
    heatLevel: "8,000 - 15,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Premium (AAA)",
    description: "Premium destemmed Byadgi. Shrivelled pods delivering intense natural red color with minimal pungency, ideal for food coloring.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "341-dry-chilli",
    name: "341 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "Popular Guntur variety. High demand in international markets for its rich red color and medium-heat pungency, ideal for general spice grinding.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "no5-dry-chilli",
    name: "No. 5 Dry Red Chilli (C5)",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Export-quality C5/No. 5 dry red chilli. Features medium-to-high pungency and a rich red appearance, widely used in commercial spice manufacturing.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "armoor-dry-chilli",
    name: "Armoor Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Robust Armoor variety dry red chilli. Known for its strong, distinctive aroma and medium pungency, highly favored in South Indian traditional recipes.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "devonur-deluxe-chilli",
    name: "DD/Devonur Deluxe Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Deluxe (AAA)",
    description: "Devonur Deluxe (DD) is a high-grade chilli offering premium visual appeal, bright crimson skins, and a well-balanced spice profile.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "teja-fatki",
    name: "Teja Fatki Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "60,000 - 80,000 SHU",
    colorValue: "40 - 50 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Fatki / Talas (B/C)",
    description: "Hand-sorted Teja Fatki. Features high heat and spice extract value at a budget-friendly wholesale price, ideal for industrial extraction.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "s10-fatki",
    name: "334 S/10 Fatki Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "20,000 - 30,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Fatki / Talas (B/C)",
    description: "Economy-grade discolored pods and husks of Sannam 334 / S10 varieties. Mostly used for mass industrial grinding and extraction.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "bullet-dry-chilli",
    name: "Bullet Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "40,000 - 55,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Short, thick, highly pungent Bullet chilli. A unique variety featuring intense heat with low seed count, perfect for premium packaging.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "chilli-26-dry",
    name: "26 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Export-quality 26 dry red chilli. Offers steady moisture compliance, standard skin thickness, and a very reliable general pungency rating.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "super10-dry-chilli",
    name: "Super 10 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "Enhanced S10 hybrid selection. Known as Super 10 due to its long pods, rich red luster, and highly consistent moderate heat value.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "bangaram-chilli-gradea",
    name: "Bangaram Quality A Grade Chilli",
    category: "Other Varieties",
    heatLevel: "15,000 - 25,000 SHU",
    colorValue: "100 - 120 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Super Deluxe (A+)",
    description: "Premium Bangaram (Gold) selection. Hand-sorted A-grade pods featuring vibrant golden-red hues, high oil content, and very low-to-moderate pungency.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "shark-dry-chilli",
    name: "Shark Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 85 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Thick-skinned Shark dry red chilli variety. Features high seed counts and strong pungency retention during shipping, making it highly requested for grinding.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "classic-dry-chilli",
    name: "Classic Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "75 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Best (AA)",
    description: "Standard general-purpose Classic red chilli. Highly versatile for domestic food services and wholesale packing distributors.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "romi26-dry-chilli",
    name: "Romi 26 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Clean-sorted Romi 26 dry red chilli. Features strong pod durability, standard seeds count, and reliable export-standard pungency levels.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "syngenta-5531-byadgi",
    name: "5531/Syngenta Byadgi Hybrid",
    category: "Other Varieties",
    heatLevel: "8,000 - 12,000 SHU",
    colorValue: "160 - 220 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "High-value Syngenta 5531 hybrid Byadgi. Famous for its deeply shrivelled pods, low heat profile, and incredibly rich natural crimson coloring.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "byadgi-335-chilli",
    name: "335 Byadgi Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "10,000 - 15,000 SHU",
    colorValue: "140 - 180 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Standard Byadgi 335 selection. Deeply shrivelled pods offering mild spice and rich coloring values, heavily used in spice oil and food coloring extraction.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "endo5-c5-chilli",
    name: "ENDO 5/C5/No. 5 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "ENDO 5 variety dry red chilli. Features moderate heat and uniform red appearance, perfect for general culinary powders and industrial processing.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "kashmiri-dry-chilli",
    name: "Kashmiri Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "8,000 - 12,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Super Deluxe (A+)",
    description: "Authentic Kashmiri dry red chilli. Internationally celebrated for giving dishes a brilliant red color with minimal heat intensity.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "wrinkle-273-chilli",
    name: "Wrinkle 273 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "12,000 - 20,000 SHU",
    colorValue: "120 - 150 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Wrinkle 273 hybrid. Offers a shrivelled appearance, rich ASTA coloring, and a mild spice kick that appeals to global culinary processors.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  }
];
