export const chilliVarieties = [
  {
    id: "teja-stem-deluxe",
    name: "S17/Teja with Stem Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Deluxe (AAA)",
    description: "Our premium Teja S17 chillies with full stems. Known for their intense heat and rich red color, they are hand-sorted to ensure you get only the finest, undamaged pods.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemcut-deluxe",
    name: "S17/Teja Stemcut Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "Stemcut",
    grade: "Deluxe (AAA)",
    description: "High-grade Teja S17 chillies with the stems neatly cut off. This allows you to pack more volume into every bag while maintaining premium quality.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemless-deluxe",
    name: "S17/Teja Stemless Deluxe",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Deluxe (AAA)",
    description: "Top-tier Teja S17 chillies with all stems carefully removed. Perfect for spice grinding mills and oil extraction plants looking for pure, ready-to-use pods.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmXIAenfi-O4aUICculJkb2c_q1geKDxYKitxFEKv9tYDEzwOveyD5RzHKwfV9ieXSc324FGyYwKG-jN-kFhmH633Psk8W6m8oliB8ZwQFdEiESIKHTAZCytcJUq672sifKtvQjWFfOqZg1PzYQKFf9BDx3MAn6Tb7mXzu8v9CjDRXdcNnB6mfaQpvdVsf0Pwnw7oZV6PJWXsGHDJSKIAHuWVb0Tm-JM2VLtgXNN8g-8-U-u5GU-dGDxb8d5jpzPknAHbWwrqOIuk"
  },
  {
    id: "teja-stem-best",
    name: "S17/Teja with Stem Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Best (AA)",
    description: "Standard grade Teja S17 with stems. A highly reliable choice that delivers the signature strong heat and bright red color at a very practical wholesale price.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemcut-best",
    name: "S17/Teja Stemcut Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "Stemcut",
    grade: "Best (AA)",
    description: "Our budget-friendly Teja S17 with cut stems. Great for buyers who want solid heat levels and need to optimize container space during shipping.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "teja-stemless-best",
    name: "S17/Teja Stemless Best",
    category: "Teja S17",
    heatLevel: "75,000 - 110,000 SHU",
    colorValue: "50 - 65 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Best (AA)",
    description: "Clean, stemless Teja S17 chillies. Hand-sorted to remove stems, making them a ready-to-mill option for wholesale spice manufacturers.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmXIAenfi-O4aUICculJkb2c_q1geKDxYKitxFEKv9tYDEzwOveyD5RzHKwfV9ieXSc324FGyYwKG-jN-kFhmH633Psk8W6m8oliB8ZwQFdEiESIKHTAZCytcJUq672sifKtvQjWFfOqZg1PzYQKFf9BDx3MAn6Tb7mXzu8v9CjDRXdcNnB6mfaQpvdVsf0Pwnw7oZV6PJWXsGHDJSKIAHuWVb0Tm-JM2VLtgXNN8g-8-U-u5GU-dGDxb8d5jpzPknAHbWwrqOIuk"
  },
  {
    id: "s4-stem-deluxe",
    name: "S4/334 with Stem Deluxe",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Deluxe (AAA)",
    description: "The famous Guntur Sannam S4 dry red chillies with stems. These feature thick skin, medium heat, and a bold red look that is highly popular in world markets.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stemless-deluxe",
    name: "S4/334 Stemless Deluxe",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Deluxe (AAA)",
    description: "Premium Guntur Sannam S4 chillies without stems. Hand-cleaned and graded to ensure clean, consistent pods for food processing and retail packing.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stem-best",
    name: "S4/334 with Stem Best",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 80 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Best (AA)",
    description: "Reliable Guntur Sannam S4 with stems. An excellent everyday choice for commercial grinding, offering good flavor and medium spice levels.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s4-stemless-best",
    name: "S4/334 Stemless Best",
    category: "S4 / 334",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 80 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Best (AA)",
    description: "Standard stemless Guntur Sannam S4 chillies. A cost-effective, ready-to-grind option for making bulk spice powders and food seasonings.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "s10-stem",
    name: "S10 with Stem",
    category: "S10",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Mild S10 chillies with stems. These have a gentle heat level and a beautiful deep red color, making them perfect for milder curry powders.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBz2O0Bku-uk1bIOLFsFezwkTk5kKyMeZbSuxeXTXF--b-6-CimtTXBKga8abM8zNGJindfw-M9BclCuLU9jsmB-1jkM83e-lejWE3pum_MTSihb_ebDcpotQUFq4ki1J8sw-BWRW7pOHPyFDRWazhdirUVX0F67s_5li3HSDFd3CsryW6zcFn7pk_ZWTx_8er_A-A2xi-JAJbCEyLovmwG9uRvba0KKcOvXUMlzFsaa5FlF3v1L0n3MgltJXI8TIw-sVG7Brk9SPQ"
  },
  {
    id: "s10-stemless",
    name: "S10 Stemless",
    category: "S10",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Standard (A/AA)",
    description: "Stemless S10 chillies offering a mild kick. Ready to be blended directly into seasoning mixes and food products that need color without heavy heat.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBz2O0Bku-uk1bIOLFsFezwkTk5kKyMeZbSuxeXTXF--b-6-CimtTXBKga8abM8zNGJindfw-M9BclCuLU9jsmB-1jkM83e-lejWE3pum_MTSihb_ebDcpotQUFq4ki1J8sw-BWRW7pOHPyFDRWazhdirUVX0F67s_5li3HSDFd3CsryW6zcFn7pk_ZWTx_8er_A-A2xi-JAJbCEyLovmwG9uRvba0KKcOvXUMlzFsaa5FlF3v1L0n3MgltJXI8TIw-sVG7Brk9SPQ"
  },
  {
    id: "byadgi-stem",
    name: "Byadgi with Stem",
    category: "Byadgi",
    heatLevel: "8,000 - 15,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Genuine, premium Byadgi chillies with stems. Famous for their deep red color and deeply wrinkled skin, they add color without the heat.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "byadgi-stemless",
    name: "Byadgi Stemless",
    category: "Byadgi",
    heatLevel: "8,000 - 15,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Premium (AAA)",
    description: "Hand-cleaned stemless Byadgi chillies. These highly shrivelled pods are perfect for extracting natural red color or making mild red food pastes.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "341-dry-chilli",
    name: "341 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "A popular Guntur variety known for its bright red color and medium heat. Highly demanded by international buyers for everyday spice blends.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "no5-dry-chilli",
    name: "No. 5 Dry Red Chilli (C5)",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Export-grade C5 chillies with stems. They offer a great balance of medium heat and rich red color, making them popular for bulk seasonings.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "armoor-dry-chilli",
    name: "Armoor Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Robust Armoor chillies featuring a thick skin and a deep, strong flavor profile. Extremely popular for traditional curry powder mixes.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "devonur-deluxe-chilli",
    name: "DD/Devonur Deluxe Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Deluxe (AAA)",
    description: "High-quality DD chillies. Known for their clean crimson skin and a smooth, mild heat that is highly versatile for cooking.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "teja-fatki",
    name: "Teja Fatki Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "60,000 - 80,000 SHU",
    colorValue: "40 - 50 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Fatki / Talas (B/C)",
    description: "Economy-grade Teja Fatki. Ideal for extraction labs looking for high heat levels at a highly competitive budget.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "s10-fatki",
    name: "334 S/10 Fatki Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "20,000 - 30,000 SHU",
    colorValue: "50 - 70 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Fatki / Talas (B/C)",
    description: "Value-grade S10/Sannam Fatki chillies. A practical option for mass grinding, providing decent color and spice at lower costs.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA0fuXQXlRkMikQ7R6Nzr9Kzgmy0jxWAeSpEL68CrdHCowl62Bef5VFP50Uyo3kQZZVVdaF2q6Sr0DwJzdoRVgtuwpcfRo17FsxKYWiC5izGDjZluRFQdLuv9xbdpZtI0XVVTA--YhoBD7jJLgaWJlbweKYex0TNykrjeATWN03tIgqD_QRLzcOlxgpl5QfXurYs8C7Bdq2C-buTYpiPixoX8dJ6IUpoJqyKyO4xE8nXnamQf6yO61Lw6mXo7M-cxbqmCkDKduvHJ8"
  },
  {
    id: "bullet-dry-chilli",
    name: "Bullet Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "40,000 - 55,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Short, plump Bullet chillies. These pack a very strong heat kick with a low seed count, making them a premium addition to spice lines.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "chilli-26-dry",
    name: "26 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Reliable 26 dry red chillies. Well-dried pods with a standard spice level, making them a steady choice for daily food production.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "super10-dry-chilli",
    name: "Super 10 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "80 - 100 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "Enhanced Super 10 chillies featuring long, bright red pods and a steady, pleasant medium heat that is highly consistent.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "bangaram-chilli-gradea",
    name: "Bangaram Quality A Grade Chilli",
    category: "Other Varieties",
    heatLevel: "15,000 - 25,000 SHU",
    colorValue: "100 - 120 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Super Deluxe (A+)",
    description: "Gold-grade Bangaram chillies. These display a gorgeous golden-red hue and very low heat, perfect for delicate spice blends.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "shark-dry-chilli",
    name: "Shark Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "35,000 - 45,000 SHU",
    colorValue: "70 - 85 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Thick-skinned Shark chillies with a high seed count. They offer strong heat and bold flavor, making them ideal for heavy spice grinding.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "classic-dry-chilli",
    name: "Classic Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "75 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Best (AA)",
    description: "General-purpose Classic red chillies. A great all-rounder for commercial kitchens, catering, and daily food services.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "romi26-dry-chilli",
    name: "Romi 26 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "25,000 - 35,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Durable Romi 26 chillies. These pods hold up well during transport and deliver a reliable, standard spice level.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "syngenta-5531-byadgi",
    name: "5531/Syngenta Byadgi Hybrid",
    category: "Other Varieties",
    heatLevel: "8,000 - 12,000 SHU",
    colorValue: "160 - 220 ASTA",
    moisture: "< 12%",
    stemType: "With Stem / Stemless",
    grade: "Premium (AAA)",
    description: "Premium Syngenta 5531 Byadgi hybrid. Deeply wrinkled skin, very low heat, and an incredibly rich red color.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "byadgi-335-chilli",
    name: "335 Byadgi Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "10,000 - 15,000 SHU",
    colorValue: "140 - 180 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Standard Byadgi 335 chillies. Shrivelled pods with a mild flavor and high color levels, perfect for extracting natural red oils.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "endo5-c5-chilli",
    name: "ENDO 5/C5/No. 5 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "30,000 - 40,000 SHU",
    colorValue: "70 - 90 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Standard (A/AA)",
    description: "Uniform ENDO 5 chillies. Offers steady medium heat and uniform red color, making them a popular base for general food processing.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVK_QZtSZ3OM9hf9u4ZtAU2E4kacKuM5CzmtoK2nLmoVbz8wDd_oa9z5VklaBFal0og_lOs34nn6ySWz5v0suvC0WeV25tMrDaQmVD5HeH2NO6CLhZSsjc5waIq3gNQsLrStJbL5JR4W0wJY-phW6UHh8x9LtRjFdKZFQpUhWJSKQ21ulOKy08DLJOriDnTvf3s67LNk83EB9jOxzYL7WL3CE75q7rqValchEu0SeEKfRnxYY4XqtmiKxYuxZAANNTj8Mt2bTb0A0"
  },
  {
    id: "kashmiri-dry-chilli",
    name: "Kashmiri Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "8,000 - 12,000 SHU",
    colorValue: "150 - 200 ASTA",
    moisture: "< 12%",
    stemType: "Stemless",
    grade: "Super Deluxe (A+)",
    description: "Kashmiri dry red chillies. Known for their deep wrinkled skin and bright crimson color, they give food a rich red look without burning.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  },
  {
    id: "wrinkle-273-chilli",
    name: "Wrinkle 273 Dry Red Chilli",
    category: "Other Varieties",
    heatLevel: "12,000 - 20,000 SHU",
    colorValue: "120 - 150 ASTA",
    moisture: "< 12%",
    stemType: "With Stem",
    grade: "Premium (AAA)",
    description: "Wrinkle 273 hybrid chillies. Features a shrunken skin, rich red color, and a pleasant, mild spice level.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIJM05ZKKYd-qGdlyk3j27bbuqrAYgNo_-T4q2qTCh_04YIEr67iAbnzrTqGnd7f5LHFvXSkYU8fomakHPZbfpyBkp8WlabOY2dKfE73S8H_g31Y-xZ2JYdAyUjLnS40k698ghnUn1aV3pk2dr__6or6khaNV0GcwlbAscAjEJYLfxD8cvxOt1OtPbofxoMZj87urg_kNj1QzBmR_5OuueEc-8yO4wT39IHIKPc2rWjhq9keJ83Ti79a2yp0iq1WW0u7n30F5nxFU"
  }
];
